name: API Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest
    env:
      workdir: ./src/Bulletin.API.Tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.workdir}}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.workdir}}

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{env.workdir}}
